name: github-actions-java

on:
  workflow_dispatch:
    inputs:
      envName: 
        default: 'test'
        required: true
  push:
    branches: 
      - main
      - release
       
  pull_request:
    branches:
      - main
      - release
 
env:
  REGION: ap-east-1 
  
  JAVA_VERSION: '1.8'
  
  
jobs:
  

  UnitTest: 
    if: github.ref == 'refs/heads/main'  || github.base_ref == 'main'
    name: Unit Test Only-test
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.myenv }}
    steps:
      - run: echo "Ref :$GITHUB_REF"
      - run: echo "$GITHUB_BASE_REF"
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.TEST }}
        run: |
            example-command "$SUPER_SECRET"
      - name: checkout
        uses: actions/checkout@v2
      

     
  UnitTest-UAT:
    if: github.ref == 'refs/heads/release'  || github.base_ref == 'release'
    name: Unit Test Only -UAT
    runs-on: ubuntu-latest
  
    steps:
      - run: echo "Ref :$GITHUB_REF"
      - run: echo "$GITHUB_BASE_REF"
      - name: checkout
        uses: actions/checkout@v2
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.TEST }}
        run: |
            example-command "$SUPER_SECRET"
  Build-UAT:
    if: github.event_name != 'pull_request' && ( needs.UnitTest-UAT.result == 'success' || github.ref == 'refs/heads/release' ) || ( needs.UnitTest.result == 'success' || github.ref == 'refs/heads/main' )
    needs: [ UnitTest-UAT, UnitTest]
    name: Build-UAT
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: pwd
      - run: tree

  Fortify-SAST:
  
    needs: Build-UAT
    runs-on: ubuntu-latest
     
    outputs:
        output1: ${{ env.JOB_TOKEN }} # try outputting job token to use in additional jobs
     
    steps:
    - uses: actions/checkout@v1
    - name: Run PowerShell Get Critical/High Count script
      run: |
        ls
          
    
  # job to get count of Critical/High vulnerabilities associated with this repo
  Fortifyanalysis:
    if: needs.Fortify-SAST.result == 'success'
    needs: Fortify-SAST # this setting makes this job dependent on build completing successfully
 
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v1
    - name: Run PowerShell Get Critical/High Count script
      run: |
        ls
 
      

  DeployArtifacts-Test:
    if: needs.Fortifyanalysis.result == 'success' 
    needs: Fortifyanalysis
    runs-on: ubuntu-latest
   # environment: TEST
    steps:
    - uses: actions/checkout@v2
    - run: echo "this job is not completed yet" 
 
  IntegrationTest:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main'
    needs: DeployArtifacts-Test 
    name: IntegrationTest
    runs-on: ubuntu-latest
   
    
    steps:
    - uses: actions/checkout@v2
    - run: echo "this job is not completed yet" 
 
   
    
  LoadTest:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main'  && success()
    needs: IntegrationTest
    name: Run Load Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Load test status - Jmeter
      run: echo "This Job would get updated soon"
