# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - main
    - release
  pull_request:
    branches: 
    - main
    - master
    - release

 
 
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.base_ref == 'main' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, worldd
  build-2:
    if: github.base_ref == 'release' || github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, worldd

  fortify-scan:
    if: github.base_ref == 'release' || github.ref == 'refs/heads/release' || github.base_ref == 'main' || github.ref == 'refs/heads/main' && always()
    needs: [ build , build-2 ]
    runs-on: ubuntu-latest
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  fortify-analysis:
    if: always()
    needs: fortify-scan
    runs-on: ubuntu-latest
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  test:
    
    if: github.base_ref == 'main' || github.ref == 'refs/heads/main'
    needs: fortify-analysis
    runs-on: ubuntu-latest
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
       # exit 1
  test-2:
    if: github.base_ref == 'release' || github.ref == 'refs/heads/release'
    needs: fortify-analysis
    runs-on: ubuntu-latest
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test 
    runs-on: ubuntu-latest
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  deploy-2:
    #if: github.ref == 'refs/heads/release'
    needs: test-2
    runs-on: ubuntu-latest
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
